<?php

declare(strict_types=1);

namespace AppBundle\Repository;

/**
 * AppointmentRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppointmentRepository extends \Doctrine\ORM\EntityRepository
{
}
